const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const services=[["🛣️","Road / Potholes","सड़क / गड्ढे"],["💧","Water Supply","जल आपूर्ति"],["🗑️","Garbage","कचरा / स्वच्छता"],["💡","Streetlights","स्ट्रीट लाइट"],["🚰","Drainage","नाली / जल निकासी"],["⚡","Electricity","बिजली"],["🌧️","Waterlogging","जलभराव"],["🚦","Traffic Signals","ट्रैफिक सिग्नल"],["🌳","Trees & Parks","पेड़ / पार्क"],["🏗️","Construction","निर्माण"],["🐕","Stray Animals","आवारा पशु"],["🧹","Cleanliness","सार्वजनिक सफाई"],["🔥","Emergency","आपातकाल"],["🛑","Road Obstruction","सड़क अवरोध"],["📢","Noise Nuisance","शोर / परेशानी"],["🏚️","Infrastructure","सार्वजनिक ढांचा"],["🚛","Waste Transport","कचरा परिवहन"],["🛶","Flooding","बाढ़"]];
$("#serviceGrid").innerHTML=services.map(c=>'<div class="service"><div>'+c[0]+'</div><b>'+c[1]+'</b><small>'+c[2]+'</small></div>').join("");
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2300)}
$$(".reveal").forEach(el=>{new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("in")}),{threshold:.08}).observe(el)});
$$("nav a").forEach(a=>a.addEventListener("click",()=>$$("nav a").forEach(n=>n.classList.toggle("active",n===a))));
$$("[data-scroll]").forEach(b=>b.addEventListener("click",()=>$(b.dataset.scroll)?.scrollIntoView({behavior:"smooth"})));
let countersStarted=false;new IntersectionObserver(es=>{es.forEach(e=>{if(!e.isIntersecting||countersStarted)return;countersStarted=true;$$("[data-count]").forEach(el=>{const target=+el.dataset.count;let n=0;const step=Math.max(1,Math.ceil(target/50));const timer=setInterval(()=>{n=Math.min(target,n+step);el.textContent=target>1000?n.toLocaleString():n;if(n>=target)clearInterval(timer)},24)})})},{threshold:.5}).observe($(".quick-stats"));
$("#imageInput")?.addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f),p=$("#imagePreview");p.classList.remove("hidden");p.innerHTML='<img src="'+url+'" alt="Uploaded civic evidence"><small style="display:block;padding:5px;font-size:9px;color:#777487">Evidence received • vision inference hook ready</small>';toast("फोटो evidence जोड़ दिया गया")});
$$(".map-filters button").forEach(btn=>btn.addEventListener("click",()=>{$$(".map-filters button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");toast(btn.textContent+" incidents selected")}));
$$(".map-pin").forEach(pin=>pin.addEventListener("click",()=>toast(pin.dataset.city+" civic incidents selected")));
$("#accessBtn")?.addEventListener("click",()=>{document.body.classList.toggle("large-type");toast(document.body.classList.contains("large-type")?"Larger text enabled":"Standard text restored")});
$("#langToggle")?.addEventListener("click",()=>{document.body.classList.toggle("hindi-mode");$("#langToggle").textContent=document.body.classList.contains("hindi-mode")?"EN":"हिं";toast(document.body.classList.contains("hindi-mode")?"Hindi emphasis enabled":"English emphasis enabled")});

/* Voice-first Saathi */
const overlay=$("#voiceOverlay"),sheet=document.querySelector(".voice-sheet"),listenOrb=$("#listenOrb"),heard=$("#heardText"),spoken=$("#spokenText"),listenLabel=$("#listenLabel"),listenHint=$("#listenHint"),voiceStatus=$("#voiceStatus"),voiceLang=$("#voiceLanguage");
let recognition=null,isListening=false,lastReply="",selectedLanguage="hi-IN";
const complaint={id:"JV-IND-0482",ward:"Ward 22",city:"Indore",department:"Road Maintenance",reports:23,nextHours:18,risk:68,days:4};
$("#wave").innerHTML=Array.from({length:35},()=>"<i></i>").join("");
function setVoiceState(state,msg){sheet.classList.toggle("listening",state==="listening");sheet.classList.toggle("speaking",state==="speaking");const c={ready:["Ready to listen · सुनने के लिए तैयार","बोलें","Tap & speak"],listening:["Listening… · सुन रहा हूँ…","सुन रहा हूँ","Stop speaking"],speaking:["Saathi is speaking · साथी जवाब दे रहा है","जवाब","Please listen"],error:["Microphone attention needed","फिर बोलें","Try again"]}[state]||["Ready","बोलें","Tap & speak"];voiceStatus.textContent=state==="speaking"?"● Speaking now":state==="listening"?"● Listening now":"● Ready";listenLabel.textContent=c[1];listenHint.textContent=c[2]}
function openVoice(){overlay.classList.add("open");overlay.setAttribute("aria-hidden","false");setVoiceState("ready");setTimeout(()=>listenOrb.focus(),80)}
function closeVoice(){stopSpeaking();stopListening();overlay.classList.remove("open");overlay.setAttribute("aria-hidden","true")}
$$("[data-voice]").forEach(b=>b.addEventListener("click",openVoice));$("#voiceClose").addEventListener("click",closeVoice);overlay.addEventListener("click",e=>{if(e.target===overlay)closeVoice()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&overlay.classList.contains("open"))closeVoice()});
function pickVoice(lang){const vs=speechSynthesis.getVoices?speechSynthesis.getVoices():[];return vs.find(v=>v.lang?.toLowerCase()===lang.toLowerCase())||vs.find(v=>v.lang?.toLowerCase().startsWith(lang.slice(0,2)))||vs.find(v=>v.lang?.toLowerCase().startsWith("en-in"))||vs[0]}
function stopSpeaking(){try{speechSynthesis.cancel()}catch(e){}sheet.classList.remove("speaking")}
function speak(text,lang=selectedLanguage){lastReply=text;if(!("speechSynthesis"in window)){setVoiceState("ready");return}stopSpeaking();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=lang.startsWith("hi")?.94:.96;u.pitch=1.02;const v=pickVoice(lang);if(v)u.voice=v;u.onstart=()=>setVoiceState("speaking");u.onend=()=>setVoiceState("ready");u.onerror=()=>setVoiceState("ready");sheet.classList.add("speaking");speechSynthesis.speak(u)}
function stopListening(){if(recognition){try{recognition.stop()}catch(e){}recognition=null}isListening=false}
function norm(t){return t.toLowerCase().replace(/[?!.,।]/g," ").replace(/\s+/g," ").trim()}
function localReply(text){const t=norm(text),hi=selectedLanguage.startsWith("hi")||/[ऀ-ॿ]|शिकायत|रिपोर्ट|स्थिति|विभाग|कब तक|गड्ढा|पानी/.test(t);
if(/status|स्थिति|रिपोर्ट.*स्थिति|शिकायत.*स्थिति|क्या हुआ|track|ट्रैक/.test(t))return hi?"जी, आपकी शिकायत "+complaint.id+" की स्थिति यह है। यह "+complaint.ward+", "+complaint.city+" में "+complaint.department+" को भेजी गई है और अभी site inspection के चरण में है। अगला action लगभग "+complaint.nextHours+" घंटे में expected है। इस incident से "+complaint.reports+" समान citizen reports जुड़ी हैं और SLA risk "+complaint.risk+" प्रतिशत है।":"Your complaint "+complaint.id+" is with "+complaint.department+", "+complaint.ward+", "+complaint.city+". It is currently in the site inspection stage. The next action is expected in about "+complaint.nextHours+" hours. "+complaint.reports+" similar citizen reports are linked to the same incident and the current SLA risk is "+complaint.risk+" percent.";
if(/how long|कब तक|कितना समय|कितने दिन|समय|eta|days|दिन/.test(t))return hi?"इस तरह की शिकायत के लिए अनुमानित resolution time लगभग "+complaint.days+" दिन है। अभी अगला field action लगभग "+complaint.nextHours+" घंटे में expected है।":"The estimated resolution time is around "+complaint.days+" days. The next field action is expected in about "+complaint.nextHours+" hours.";
if(/department|विभाग|कौन.*देख|कौन.*जिम्मेदार|officer|अधिकारी/.test(t))return hi?"आपकी शिकायत "+complaint.department+" विभाग के पास है, "+complaint.ward+", "+complaint.city+" में। JanVaani location और issue type के आधार पर इसे responsible civic authority तक route करता है।":"Your complaint is assigned to "+complaint.department+", "+complaint.ward+", "+complaint.city+". JanVaani uses location and issue type to route it to the responsible civic authority.";
if(/report|नई शिकायत|शिकायत दर्ज|register|दर्ज कर|problem|समस्या/.test(t))return hi?"बिल्कुल। मैं आपके साथ voice में शिकायत दर्ज करूँगा। अपने शब्दों में समस्या बताइए और संभव हो तो नज़दीकी landmark भी बताइए।":"Absolutely. I can take the complaint by voice. Tell me the problem in your own words and, if possible, mention the nearest landmark.";
if(/hello|hi|hey|namaste|नमस्ते|नमस्कार/.test(t))return hi?"नमस्ते। मैं साथी हूँ। आप शिकायत की स्थिति, विभाग या समाधान का अनुमान पूछ सकते हैं। या अपनी नई समस्या बोल सकते हैं।":"Hello. I’m Saathi. You can ask about complaint status, department, expected time, or tell me a new civic problem.";
return hi?"जी, मैं सुन रहा हूँ। आप सीधे पूछ सकते हैं — मेरी शिकायत की स्थिति क्या है, कितने दिन लगेंगे, या कौन सा विभाग इसे देख रहा है?":"I’m listening. Ask about your complaint status, expected time, or the responsible department."}
async function getReply(text){try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),1800),r=await fetch((window.JANVAANI_API_BASE||"http://127.0.0.1:8000")+"/api/v1/voice/respond",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:text,language:selectedLanguage}),signal:controller.signal});clearTimeout(timer);if(r.ok){const d=await r.json();if(d&&d.reply_text)return d.reply_text}}catch(e){}return localReply(text)}
async function handleText(text){heard.textContent="“"+text+"”";setVoiceState("speaking","Thinking… · समझ रहा हूँ…");const reply=await getReply(text);spoken.textContent=reply;speak(reply,selectedLanguage)}
function startListening(){if(isListening){stopListening();setVoiceState("ready");return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast("Chrome speech recognition is required for voice input.");setVoiceState("error","Use Chrome or connect Indic ASR.");return}stopSpeaking();recognition=new SR();recognition.lang=selectedLanguage;recognition.interimResults=true;recognition.continuous=false;recognition.maxAlternatives=1;recognition.onstart=()=>{isListening=true;setVoiceState("listening");heard.textContent="“सुन रहा हूँ…”"};recognition.onresult=e=>{let final="",interim="";for(let i=e.resultIndex;i<e.results.length;i++){const s=e.results[i][0].transcript;e.results[i].isFinal?final+=s:interim+=s}heard.textContent="“"+(final||interim)+"”";if(final)handleText(final)};recognition.onerror=e=>{isListening=false;setVoiceState("error",e.error==="not-allowed"?"Microphone permission denied · Mic permission दें":"Could not hear clearly · फिर बोलें");toast(e.error==="not-allowed"?"Please allow microphone access.":"I couldn't hear that clearly.")};recognition.onend=()=>{isListening=false;recognition=null;if(!sheet.classList.contains("speaking"))setVoiceState("ready")};try{recognition.start()}catch(e){setVoiceState("error")}}
listenOrb.addEventListener("click",startListening);$("#repeatVoice").addEventListener("click",()=>lastReply?speak(lastReply):toast("पहले Saathi से बात करें."));$("#stopVoice").addEventListener("click",stopSpeaking);voiceLang.addEventListener("change",()=>{selectedLanguage=voiceLang.value;setVoiceState("ready",selectedLanguage==="hi-IN"?"Hindi voice ready · हिंदी आवाज़ तैयार":"English voice ready")});$$("[data-say]").forEach(b=>b.addEventListener("click",()=>{const t=b.dataset.say;heard.textContent="“"+t+"”";handleText(t)}));if("speechSynthesis"in window&&speechSynthesis.addEventListener)speechSynthesis.addEventListener("voiceschanged",()=>speechSynthesis.getVoices());setVoiceState("ready");
